// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJckVJvWZhevZPREl4J4eYhD8B6dTXEhU',
    appId: '1:1011593100210:web:aaaf8340847b22070742ab',
    messagingSenderId: '1011593100210',
    projectId: 'tourtravel-26f56',
    authDomain: 'tourtravel-26f56.firebaseapp.com',
    databaseURL: 'https://tourtravel-26f56-default-rtdb.firebaseio.com',
    storageBucket: 'tourtravel-26f56.firebasestorage.app',
    measurementId: 'G-GMRMVNM2DT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBz3dm7DbFv9xoJPlP092BKhqd0pWU8lqc',
    appId: '1:1011593100210:android:abb3c6f5f0c74ba10742ab',
    messagingSenderId: '1011593100210',
    projectId: 'tourtravel-26f56',
    databaseURL: 'https://tourtravel-26f56-default-rtdb.firebaseio.com',
    storageBucket: 'tourtravel-26f56.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAR9Zlk4u1pEDR5DPYwLNqh-7kUtFQmb9c',
    appId: '1:1011593100210:ios:c00765fb124083600742ab',
    messagingSenderId: '1011593100210',
    projectId: 'tourtravel-26f56',
    databaseURL: 'https://tourtravel-26f56-default-rtdb.firebaseio.com',
    storageBucket: 'tourtravel-26f56.firebasestorage.app',
    iosBundleId: 'com.example.tourtravel',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJckVJvWZhevZPREl4J4eYhD8B6dTXEhU',
    appId: '1:1011593100210:web:e640de8ee083f1d00742ab',
    messagingSenderId: '1011593100210',
    projectId: 'tourtravel-26f56',
    authDomain: 'tourtravel-26f56.firebaseapp.com',
    databaseURL: 'https://tourtravel-26f56-default-rtdb.firebaseio.com',
    storageBucket: 'tourtravel-26f56.firebasestorage.app',
    measurementId: 'G-VSQG6H1140',
  );

}